# Generated by Django 5.2.15 on 2026-07-04 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('fecha_prediccion', models.DateField(blank=True, null=True)),
                ('franja_horaria', models.CharField(blank=True, max_length=20)),
                ('pedidos_estimados', models.FloatField(blank=True, null=True)),
                ('franja_critica', models.CharField(blank=True, max_length=20)),
                ('nivel_demanda', models.CharField(blank=True, max_length=30)),
                ('productos_top', models.JSONField(blank=True, default=list)),
                ('recomendaciones', models.JSONField(blank=True, default=dict)),
                ('parametros_entrada', models.JSONField(blank=True, default=dict)),
                ('resultado_detallado', models.JSONField(blank=True, default=dict)),
                ('modelo_demanda_usado', models.CharField(blank=True, max_length=100)),
                ('modelo_producto_usado', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('error', 'Error')], default='generado', max_length=20)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('training_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones', to='machine_learning.trainingrun')),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
