# Generated by Django 5.2.15 on 2026-07-04 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entrenado', 'Entrenado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('modelo_seleccionado_demanda', models.CharField(blank=True, max_length=100)),
                ('mae_demanda', models.FloatField(blank=True, null=True)),
                ('rmse_demanda', models.FloatField(blank=True, null=True)),
                ('r2_demanda', models.FloatField(blank=True, null=True)),
                ('modelo_seleccionado_producto', models.CharField(blank=True, max_length=100)),
                ('mae_producto', models.FloatField(blank=True, null=True)),
                ('rmse_producto', models.FloatField(blank=True, null=True)),
                ('r2_producto', models.FloatField(blank=True, null=True)),
                ('metricas_detalladas', models.JSONField(blank=True, default=dict)),
                ('variables_usadas_demanda', models.JSONField(blank=True, default=list)),
                ('variables_usadas_producto', models.JSONField(blank=True, default=list)),
                ('importancia_variables', models.JSONField(blank=True, default=list)),
                ('ruta_modelo_demanda', models.CharField(blank=True, max_length=255)),
                ('ruta_modelo_producto', models.CharField(blank=True, max_length=255)),
                ('graficos', models.JSONField(blank=True, default=dict)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('tiempo_entrenamiento_segundos', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenamientos', to='datasets.datasetupload')),
            ],
            options={
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
    ]
